# Generating flowchart diagram
# for getTemplateIndirect() in TemplateTools.py
# Version 4.0

from graphviz import Digraph
import os


current_path = os.path.abspath(__file__)
os.chdir(os.path.dirname(current_path))
# os.environ["PATH"] = 'T:\Graphviz'

# dot = Digraph(comment='The Flowchart Diagram', format="png")
dot = Digraph(comment='The Flowchart Diagram')

# dot.node('0', 'START')

dot.node('a', 'IF "Medical Student"')
dot.node('a1', '"Cardiology"')
dot.node('a2', 'Cardiology Med Student')
dot.node('a3', 'Medical Student')
dot.edge('a', 'a1', 'Y')
dot.edge('a1', 'a2', 'Y')
dot.edge('a1', 'a3', 'N')

# dot.node('b', 'ELSEIF "Foundation Year"')
# dot.node('b1', '"General Practice" OR "Emergency"')
# dot.node('b2', 'ED FY Doctor')
# dot.node('b3', 'Foundation Year Doctor')
# dot.edge('b', 'b1', 'Y')
# dot.edge('b1', 'b2', 'Y')
# dot.edge('b1', 'b3', 'N')
dot.node('z', ' ELSEIF "Dental Student"')
dot.edge('z', 'a1', 'Y')

dot.node('b', 'ELSEIF "Foundation Year"')
dot.node('b1', '"General Practice" OR "Emergency"')
# dot.node('b2', 'ED FY Doctor')
dot.node('b3', 'Foundation Year Doctor')
dot.edge('b', 'b1', 'Y')
# dot.edge('b1', 'b2', 'Y')
dot.edge('b1', 'b3', 'N')

# dot.node('c', 'ELSEIF "Radiologist"')
# dot.node('c1', '"Consultant"')
# dot.node('c2', 'Consultant Radiologist')
# dot.node('c3', 'ST1-4 Radiologist')
# dot.edge('c', 'c1', 'Y')
# dot.edge('c1', 'c2', 'Y')
# dot.edge('c1', 'c3', 'N')

dot.node('d', 'ELSEIF "Anaesthetist" OR "Anaesthetics" OR "Pain"')
dot.node('d1', '"Care" OR "Clinical Informatics" OR "Cancer" OR "Consultant"')
dot.node('d2', '"Medicine" OR "Gastroenterology" OR "Medical Department - Anaesthetics" OR "Theatres" OR "Registrar" '
               'OR' "Trust")
dot.node('d3', "Anaesthetist")
dot.node('d4', "Named Consultant Anaesthetist")
dot.edge('d', 'd1', 'Y')
dot.edge('d1', 'd4', 'Y')
dot.edge('d1', 'd2', 'N')
dot.edge('d2', 'd3', 'Y')

# dot.node('d2', 'Anaesthetist')
# dot.node('d3', 'Named Consultant Anaesthetist')
# dot.edge('d', 'd1', 'Y')
# dot.edge('d1', 'd2', 'Y')
# dot.edge('d1', 'd3', 'N')

# dot.node('e', 'ELSEIF "General Practitioner"')
# dot.node('e1', 'ED Consultant')
# dot.edge('e', 'e1', 'Y')

dot.node('f', 'ELSEIF "Surgeon" OR "Surgery" OR "Surgical" OR "Urology" NOT "Neurology" OR "Cardiothoracic" OR '
              '"Thoracic" OR "Oral" OR "Maxillofacial" OR "Plastic" OR "Trauma" OR "Orthopaedics" OR "Vascular"')
# dot.node('f1', '"Associate" OR "Registrar"')
# dot.node('f2', 'Surgeon')
# dot.node('f3', 'Surgeon Consultant')
dot.node('f1', '"Consultant"')
dot.node('f2', 'Surgeon Consultant')
dot.node('f3', 'Surgeon')
dot.edge('f', 'f1', 'Y')
dot.edge('f1', 'f2', 'Y')
dot.edge('f1', 'f3', 'N')

dot.node('g', 'ELSEIF "Consultant"')
dot.node('g1', '"Cardiology"')
dot.node('g2', '"General Practice" OR "Emergency Medicine"')
dot.node('g3', '"Anaesthetics" OR "Intensive Care Medicine"')
dot.node('g4', '"Oncology" OR "Haematology"')
dot.node('g5', 'Cardiologist')
dot.node('g6', 'ED Consultant')
dot.node('g7', 'Named Consultant Anaesthetist')
dot.node('g8', 'Consultant (Oncology)')
dot.node('g9', 'Consultant (all types)')
dot.edge('g', 'g1', 'Y')
dot.edge('g1', 'g5', 'Y')
dot.edge('g1', 'g2', 'N')
dot.edge('g2', 'g6', 'Y')
dot.edge('g2', 'g3', 'N')
dot.edge('g3', 'g7', 'Y')
dot.edge('g3', 'g4', 'N')
dot.edge('g4', 'g8', 'Y')
dot.edge('g4', 'g9', 'N')

dot.node('h', 'ELSEIF "Specialty" OR "Specialist"')
dot.node('h1', '"Associate" OR "Registrar"')
dot.node('h2', '"Cardiology"')
dot.node('h3', '"General Practice" OR "Emergency Medicine"')
dot.node('h4', '"Anaesthetics" OR "Intensive Care Medicine"')
dot.node('h4+', '"Anaesthetics" OR "Intensive Care Medicine"')
dot.node('h5', '"Oncology" OR "Haematology"')
dot.node('h6', 'Cardiology Registrar')
dot.node('h7', 'ED Physician')
dot.node('h8', 'Anaesthetist')
dot.node('h9', 'Doctor - ST1+ (SpR/SHO)')
dot.node('h10', 'Named Consultant Anaesthetist')
dot.node('h11', 'Consultant (Oncology)')
dot.node('h12', 'Consultant (all types)')
dot.edge('h', 'h1', 'Y')
dot.edge('h1', 'h2', 'Y')
dot.edge('h1', 'h4+', 'N')
dot.edge('h2', 'h6', 'Y')
dot.edge('h2', 'h3', 'N')
dot.edge('h3', 'h7', 'Y')
dot.edge('h3', 'h4', 'N')
dot.edge('h4', 'h8', 'Y')
dot.edge('h4', 'h9', 'N')
dot.edge('h4+', 'h10', 'Y')
dot.edge('h4+', 'h5', 'N')
dot.edge('h5', 'h11', 'Y')
dot.edge('h5', 'h12', 'N')

dot.node('i', 'ELSE')
dot.node('i1', '0NOT_KNOWN')
dot.edge('i', 'i1')

# dot.edges(['0a', '0b', '0c', '0d', '0e', '0f','0g', '0h', '0i',])

# dot.edge('a', 'b', 'N')
dot.edge('a', 'z', 'N')
dot.edge('z', 'b', 'N')
dot.edge('b', 'd', 'N')
# dot.edge('c', 'd', 'N')
# dot.edge('d', 'e', 'N')
dot.edge('d', 'f', 'N')
dot.edge('f', 'g', 'N')
dot.edge('g', 'h', 'N')
dot.edge('h', 'i', 'N')
# dot.edge('0', 'b', '')

# dot.view()
# print(dot.source)

dot.render('results/TemplateCheckFlowchart-v4.0.gv', view=True)
